name: Build and NUGET.org publish

on:
  push:
    tags:
    - '*.*'
    - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Install dependencies
      run: dotnet restore --source https://api.nuget.org/v3/index.json
    - name: Build
      run: dotnet build --configuration Release --no-restore -property:ContinuousIntegrationBuild=true
    - name: UnitTests
      run: dotnet test --configuration Release --no-restore --no-build --verbosity normal --logger trx Tests/UnitTests
    - name: Create Package
      run: dotnet pack --configuration Release --no-restore --no-build --version-suffix $RELEASE_VERSION
    #- name: Publish Package on Nuget.org
    #  run: dotnet nuget push "**/bin/Release/*.nupkg" --source https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_PUBLISH_APIKEY }} --skip-duplicate 
